-- NOTE: This file is auto generated by ./sql-generator

-- AudioFingerprintRepository.upsert
insert into
  "audio_fingerprint" ("assetId", "fingerprint", "duration")
values
  ($1::uuid, $2::integer[], $3)
on conflict ("assetId") do update
set
  "fingerprint" = $4::integer[],
  "duration" = $5

-- AudioFingerprintRepository.getCandidates
select
  "audio_fingerprint"."assetId",
  "audio_fingerprint"."fingerprint",
  "audio_fingerprint"."duration",
  "asset"."duplicateId"
from
  "audio_fingerprint"
  inner join "asset" on "asset"."id" = "audio_fingerprint"."assetId"
where
  "asset"."ownerId" = $1::uuid
  and "asset"."deletedAt" is null
  and abs(audio_fingerprint.duration - $2) / greatest(audio_fingerprint.duration, $3, 1) < $4
